version: "3.9"
services:
  nginx:
    image: nginx:1.27.0
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - php
  php:
    build: ./php
    volumes:
      - .:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    depends_on:
      - db
    working_dir: /var/www/html/app
    tty: true
  db:
    image: mysql:8.4.0
    environment:
      MYSQL_ROOT_PASSWORD: conviction
      MYSQL_DATABASE: convi
      MYSQL_USER: user
      MYSQL_PASSWORD: conviction
    ports:
      - "3306:3306"
    volumes:
      - ./db/mysql:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
